import type { Metadata } from "next";
import "./globals.css";
import LayoutHeader from "@/components/header";
import { manrope, tinos } from "@/data/font";
import LayoutFooter from "@/components/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={manrope.className}>
      <LayoutHeader />
        {children}
        <LayoutFooter />
        </body>
    </html>
  );
}
